version: '3'
services:
  webserver:
    image: 
      nginx:alpine
    restart: 
      always
    tty: 
      true
    ports:
      - "$WEBSERVER_PORT:80"
    networks:
      - net
    volumes:
      - ../../frontend/:/usr/share/nginx/html

  pg_db:
    image: 
      postgres:13.1
    restart: 
      always
    environment:
      POSTGRES_PASSWORD: $DB_PASS
      POSTGRES_USER: $DB_USER
      POSTGRES_DB: $DB_NAME
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "$DB_PORT:5432"
    networks:
      net:

  pgmyadmin:
    image: 
      dpage/pgadmin4 
    ports:
      - "$PGADMIN_PORT:80"
    environment:
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
    networks:
      net:


  backend:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ../../
      dockerfile: ./docker/hackaton_instances/dockerfiles/spring.Dockerfile
    ports:
      - "$SPRING_PORT:8080"
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://pg_db:$DB_PORT/$DB_NAME
      - SPRING_DATASOURCE_USERNAME=$DB_USER
      - SPRING_DATASOURCE_PASSWORD=$DB_PASS
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      net:

volumes:
  db:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        -
          subnet: $NETWORK
